### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by OmriHarary** [florisheyvaert/Blace#3]
Hi there, it would be really appreciated if you could add a license to this package since [not including one actually limits its usability significantly](https://choosealicense.com/no-permission/).

Unless you already have a strong preference, the [MIT license](https://choosealicense.com/licenses/mit/) is nice, simple, and permissive.

**Comment by florisheyvaert** [comment]
Hello, 

Just added the MIT license, hope this helps for you.
